dist: trusty
sudo: false

language: node_js
node_js:
    - '10'

cache:
    directories:
        - ./node_modules

install:
    - npm install

jobs:
    include:
        - stage: build
          if: type = push AND branch != master OR type = pull_request
          name: 'Building Application ...'
          script: npm run ng:build
        - stage: build
          if: type = push AND branch = master
          name: 'Building Application ...'
          script: npm run pack
         
deploy:
  provider: releases
  api_key: ${api_key}
  file_glob: true
  file: "**/*.deb"
  skip_cleanup: true
  on:
    all_branches: true