version: 2.1
orbs:
  node: circleci/node@1.1.6
jobs:
  lint:
    executor:
      name: node/default
    steps:
      - checkout
      - node/with-cache:
          steps:
            - run: npm install
            - run: npm run lint
  electron-build:
    executor:
      name: node/default
    steps:
      - checkout
      - node/with-cache:
          steps:
            - run: npm install
            - run: npm run electron:build
      - persist_to_workspace:
          root: /home/circleci/project
          paths: dist_electron
  publish-github-release:
    docker:
      - image: circleci/golang:1.8
    steps:
      - attach_workspace:
          at: ./wks
      - run:
          name: "Get package version"
          command: |
            PACKAGE_VERSION=$(cat ./wks/dist_electron/package.json \
            grep version \
            head -1 \
            awk -F: '{ print $2 }' \
            sed 's/[",]//g')
      - run:
          name: "Version is..."
          command: echo $PACKAGE_VERSION
      - run:
          name: "What's in the workspace??"
          command: |
            ls ./wks
    
workflows:
  version: 2
  lint-and-build:
    jobs:
      - lint
      - electron-build:
          requires:
            - lint
      - publish-github-release:
          requires:
            - lint
            - electron-build
