directories:
  output: package
  buildResources: build
  app: dist_electron/bundled
files:
  - filter:
      - '**'
extends: null
appId: octotouch
productName: OctoTouch
linux:
  target:
    - target: deb
      arch:
        - armv7l
  category: Utility
electronVersion: 6.1.10
